# Generated by Django 4.0.2 on 2022-02-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
